server:
  port: 8081

spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.60.128:9092 #192.168.60.128
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 192.168.60.128:9092
      group-id: msgGroup
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  rabbitmq:
    host: 192.168.60.128
    port: 5672
    username: admin
    password: 123456